# this is an example & functional config containing various steps for 2 slots

# slot (0, 0)
- slot:
      period: 0
      thread: 0
  execution_steps:
      - name: save_user_address_on_ledger
        config:
            type: write_ledger_entry
            address: user_address
            balance: 5000000000000
      # deploy ERC20
      - name: deploy_usdc_on_ledger
        config:
            type: write_ledger_entry
            address: usdc
            bytecode: ./../dex/v2.1/build/ERC20.wasm
            balance: 0
      # initialize the previously deployed ERC20
      - name: initialize_usdc
        config:
            type: call_sc
            address: usdc
            function: constructor
            parameter:
                [
                    8,
                    0,
                    0,
                    0,
                    85,
                    83,
                    68,
                    32,
                    67,
                    111,
                    105,
                    110,
                    4,
                    0,
                    0,
                    0,
                    85,
                    83,
                    68,
                    67,
                    9,
                    0,
                    202,
                    154,
                    59,
                    0,
                    0,
                    0,
                    0,
                ]
            gas: 4294967295
            call_stack:
                - address: user_address
                  coins: 32
      # call the name function
      - name: call_name_function
        config:
            type: call_sc
            address: usdc
            function: name
            parameter:
                [117, 115, 101, 114, 95, 97, 100, 100, 114, 101, 115, 115]
            gas: 4294967295
            call_stack:
                - address: user_address
                  coins: 32
      - name: call_balanceOf_function
        config:
            type: call_sc
            address: usdc
            function: balanceOf
            parameter:
                [
                    12,
                    0,
                    0,
                    0,
                    117,
                    115,
                    101,
                    114,
                    95,
                    97,
                    100,
                    100,
                    114,
                    101,
                    115,
                    115,
                ]
            gas: 4294967295
            call_stack:
                - address: user_address
                  coins: 32
