# In this config, we are executing several steps (see comments) at slot (0, 0)
- slot:
    period: 0
    thread: 0
  execution_steps:
    - name: setup_initial_address # Add coins to given address
      config:
        type: write_ledger_entry
        address: X6Jqk749Dk8= # credit this address
        balance: 789000
    - name: execute_main # Execute smart contract at given path
      config:
        type: execute_sc
        path: ../massa-sc-examples/async-calls/build/main.wasm
        function: main
        parameter: ''
        gas: 100000
        call_stack:
          - address: X6Jqk749Dk8= # execute caller
            coins: 100
    - name: setup_initial_address_2 # Add coins + smart contract (aka bytecode) to given address
      config:
        type: write_ledger_entry
        address: yvgsOkbC54I=
        bytecode: ../massa-sc-examples/async-calls/build/smart-contract.wasm
        balance: 876500
    - name: call_function # Call function from smart contract
      config:
        type: call_sc
        address: yvgsOkbC54I= # smart contract address
        function: receive
        parameter: test
        gas: 100000
        call_stack:
          - address: X6Jqk749Dk8= # smart contract caller
            coins: 100
    - name: read_events_after_execution # read events generated by smart contract (1 event should be gen. from receive call)
      config:
        type: read_events
        start:
          period: 0
          thread: 0
        end:
          period: 4
          thread: 16
    - name: read_main_address_ledger_entry # read balance
      config:
        type: read_ledger_entry
        address: X6Jqk749Dk8=
    - name: write_new_random_async_message # send an async message
      config:
        type: write_async_message
        sender_address: X6Jqk749Dk8=
        target_address: yvgsOkbC54I=
        target_handler: receive
        execution_slot: # will be exec at this slot
          period: 2
          thread: 6
        gas: 100000
        coins: 100
        data: hello from the otherside # data sent via async message
    - name: read_all_messages_after_steps
      config:
        type: read_async_messages
        start:
          period: 0
          thread: 0
        end:
          period: 8
          thread: 12
