name: CD

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: windows
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            name: linux
          - os: macos-latest
            target: x86_64-apple-darwin
            name: macos-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            name: macos-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-11-13
          target: ${{ matrix.target }}
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Build
        shell: bash
        run: |
          OPTS=""
          if [[ "${{ matrix.name }}" == "macos-arm64" ]]; then
            OPTS="--target=${{ matrix.target }}"
          fi
          cargo build --release $OPTS
      - name: Package
        shell: bash
        run: |
          OUTPUT_DIR="target"
          if [[ "${{ matrix.name }}" == "macos-arm64" ]]; then
            OUTPUT_DIR="target/${{ matrix.target }}"
          fi

          mkdir massa
          cp ${OUTPUT_DIR}/release/massa-sc-tester massa/
          if [[ "${{ matrix.name }}" == "windows" ]]
          then
            7z a release_${{ matrix.name }}.zip massa
          else
            tar czvf release_${{ matrix.name }}.tar.gz massa
          fi
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "release_*"
